sudo: required
services:
- docker
before_install:
- docker build -t vetalxpro/react-test -f ./client/Dockerfile.dev ./client

script:
- docker run vetalxpro/react-test npm test -- --coverage

after_success:
- docker build -t vetalxpro/multi-docker-client ./client
- docker build -t vetalxpro/multi-docker-nginx ./nginx
- docker build -t vetalxpro/multi-docker-server ./server
- docker build -t vetalxpro/multi-docker-worker ./worker
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push vetalxpro/multi-docker-client
- docker push vetalxpro/multi-docker-nginx
- docker push vetalxpro/multi-docker-server
- docker push vetalxpro/multi-docker-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-970650818193
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
