version: '3'
services:
  nginx:
    #    container_name: 'nginx'
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
    - api
    - client
    ports:
    - 80:80
  postgres:
    image: postgres
  #    container_name: 'postgres'
  redis:
    image: redis
  #    container_name: 'redis'
  api:
    #    container_name: 'server'
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - PG_USER=postgres
    - PG_HOST=postgres
    - PG_DATABASE=postgres
    - PG_PASSWORD=postgres_password
    - PG_PORT=5432
    volumes:
    - /app/node_modules
    - ./server:/app
    depends_on:
    - postgres
    - redis
  worker:
    #    container_name: 'worker'
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    volumes:
    - /app/node_modules
    - ./worker:/app
    depends_on:
    - redis
  client:
    #    container_name: 'client'
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
    - /app/node_modules
    - ./client:/app
    depends_on:
    - api
